bcgov/nr-bcwat

client/src/App.vue, client/src/assets/shared-styles.scss, client/src/assets/variables.scss, client/src/components/NavBar.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/watershed/Watershed.vue, client/src/components/watershed/WatershedReport.vue, client/src/style.css
Reduce nav bar size and create watershed report template
=> Create reusable report component

client/src/assets/shared-styles.scss, client/src/components/watershed/Watershed.vue, client/src/components/watershed/WatershedReport.vue, client/src/components/watershed/report/Allocations.vue, client/src/components/watershed/report/AllocationsByIndustry.vue, client/src/components/watershed/report/AnnualHydrology.vue, client/src/components/watershed/report/Climate.vue, client/src/components/watershed/report/HydrologicVariability.vue, client/src/components/watershed/report/Landcover.vue, client/src/components/watershed/report/Methods.vue, client/src/components/watershed/report/MonthlyHydrology.vue, client/src/components/watershed/report/Notes.vue, client/src/components/watershed/report/References.vue, client/src/components/watershed/report/Topography.vue, client/src/components/watershed/report/WatershedIntroduction.vue, client/src/components/watershed/report/WatershedOverview.vue
Create Report Table of Contents
User can click on a section in sidebar to scroll to it
Scrolling in the report highlights whichever section you scroll past
=> Bcwat 86 report toc

client/src/components/streamflow/Streamflow.vue
Modified the streamflow sidebar to work similarly to the watershed page for style and functional consistency. 
Functionality copied over to the streamflow page. 
None
=> BCWAT 12 Adjust Streamflow Sidebar

.github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/new_task.md
=> Added a new template for new issues

client/src/assets/variables.scss, client/src/components/watershed/report/AnnualHydrology.vue, client/src/components/watershed/report/Landcover.vue, client/src/components/watershed/report/MonthlyHydrology.vue, client/src/components/watershed/report/MonthlyHydrologyChart.vue, client/src/components/watershed/report/MonthlyHydrologyLegend.vue, client/src/components/watershed/report/MonthlyHydrologyTable.vue, client/src/constants/dateHelpers.js
Recreate Monthly Hydrology Section including:
- Stacked Bar Chart with legend
- table
for both the query and downstream watersheds
=> 21 recreate watershed report monthly hydrology

client/src/assets/shared-styles.scss, client/src/assets/variables.scss, client/src/components/watershed/WatershedReport.vue, client/src/components/watershed/report/Climate.vue, client/src/components/watershed/report/ClimateChart.vue, client/src/components/watershed/report/Landcover.vue, client/src/components/watershed/report/MonthlyHydrologyChart.vue, client/src/components/watershed/report/Topography.vue
Recreate the topography and climate sections in the watershed report
=> 26 recreate watershed report climate

airflow/dags/env_hydro_dag.py, airflow/dags/flow_works_dag.py, airflow/dags/gw_moe_dag.py, airflow/dags/wsc_hydro_dag.py, airflow/etl_pipelines/scrapers/StationObservationPipeline/StationObservationPipeline.py, airflow/pod_templates/medium_task_template.yaml, airflow/pod_templates/simple_task_template.yaml
- Added `flow_works_dag.py` to the list of dags
- Added key value pair to the secrets for the FlowWorks API access to the pod template files
- They have been added to the on-prem Project as well
This will close #49 
=> flow_work_dag and secerets added

airflow/pod_templates/medium_task_template.yaml, airflow/pod_templates/simple_task_template.yaml, charts/airflow/README.md, charts/airflow/values.base.yaml
Manually create a fernet key on metadata DB for encryption
=> Fix Fernet Key

airflow/pod_templates/medium_task_template.yaml, airflow/pod_templates/simple_task_template.yaml
turn on PVC for medium task logs
=> Enable Medium Task Persistent Logs

airflow/etl_pipelines/scrapers/StationObservationPipeline/water/flow_works.py
Minor change to make sure that dot env can load
=> added dotenv and try block

client/src/components/climate/ClimateReport.vue, client/src/components/climate/report/ClimateReportChart.vue
Turn the Precipitation chart component into a resuable component that can be used for precipitation, temperature, snow water equivalent and snow of ground charts in the Climate report
=> Adapt climate chart

airflow/etl_pipelines/scrapers/StationObservationPipeline/StationObservationPipeline.py
Quotation issues has been fixed.
=> fix quotation issues

airflow/etl_pipelines/scrapers/StationObservationPipeline/StationObservationPipeline.py
Clean Up Query for Flowworks Scraper
=> Clean Up Query

charts/nfs-server/okd/persistentvolume.yaml
Change Path for Airflow Logs Persistent Volume
This is already applied, testing, and working.
=> update PV path

charts/nfs-server/okd/persistentvolume.yaml, client/package-lock.json, client/package.json, client/src/components/streamflow/FlowDuration.vue, client/src/components/streamflow/SevenDayFlow.vue, client/src/components/streamflow/StreamflowReport.vue, client/src/components/streamflow/StreamflowStage.vue
Added a Stage chart which uses the seven day flow chart component, substituting the flow y axis label for "Stage (m)" 
This stage chart leverages the seven day flow chart and presents the data in an identical format. Once we have the data structure for this chart, it can be used to populate the chart instead.
=> bcwat-58-streamflow-stage

client/src/components/MapSearch.vue, client/src/components/climate/ClimatePage.vue, client/src/components/climate/ClimateReport.vue, client/src/components/groundwater/GroundWater.vue, client/src/components/groundwater/GroundWaterQualityReport.vue, client/src/components/streamflow/SevenDayFlow.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/streamflow/StreamflowReport.vue, client/src/components/surfacewater/SurfaceWater.vue, client/src/components/surfacewater/SurfaceWaterQualityReport.vue, client/src/components/watershed/Watershed.vue, client/src/components/watershed/report/WatershedOverview.vue
This feature adds a search bar with various options to each page with a map. 
- Added search bar component
- Added search input
- Added search type dropdown selector
- Added constants for Streamflow, Watershed, Climate, Surface Water, and Ground Water that define the searchable types for each page. 
Some of search options are specific to certain pages. For instance, some pages don't have station names, so this option is omitted. Further search options can be added easily as needed by updating the "...SearchTypes" constants in each component.
=> bcwat-113-add-map-search

backend/README.md, backend/database_initialization/README.md, backend/database_initialization/all_data_transfer.py
README.md for the `database_initialization` directory! 
Closes #141
=> Bcwat 141 add documentation to database init

client/src/components/MapPointSelector.vue, client/src/components/climate/ClimatePage.vue, client/src/components/climate/ClimateReport.vue, client/src/components/groundwater/GroundWater.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/surfacewater/SurfaceWater.vue, client/src/components/watershed/Watershed.vue
Adds a reusable component that provides a listing of all points located underneath the user's cursor when multiple points are close together and overlapping. 
=> bcwat-147 overlapping point selector

client/src/components/climate/report/ClimateReportChart.vue
Incorporate chart legend into climate chart svg so it is included in the png download.
=> 151 climate report chart legend

airflow/README.md, airflow/etl_pipelines/README.md, documentation/Architecture.md
Documentation on the structure of DAGs, architecture, and the sources that the scrapers are scraping from have been improved.
Please let me know if you want me to fill out some other sections as well! 
closes #176
=> Enhanced docs

client/cypress/component/groundwater-level/GroundWaterLevelReport.cy.js, client/cypress/component/groundwater-level/GroundwaterLevel.cy.js, client/cypress/support/component-index.html, client/src/components/groundwater-level/GroundWaterLevelReport.vue, client/src/components/streamflow/StreamflowReport.vue
Added some simple tests to test the components related to the Groundwater Level page. 
=> bcwat-163-groundwater-unit-testing

airflow/dags/quarterly_hydat_import_dag.py, airflow/etl_pipelines/scrapers/QuarterlyPipeline/quarterly/hydat_import.py
- Forgot to call `extract_data()` in the dag
- Added `clean_up()` function to remove downloaded files
- 
=> Stations fix and clean up

client/cypress/e2e/Tour.cy.js, client/package-lock.json, client/src/App.vue, client/src/components/NavBar.vue, client/src/components/Tour.vue
Adds a short, guided tour on what the pages are and what appears in the sidebar, where to find the search. 
Added a custom Tour.vue component to handle the tour highlighting and control
=> bcwat-223-add-tour

client/cypress/e2e/Climate.cy.js, client/cypress/e2e/GroundWaterLevel.cy.js, client/cypress/e2e/GroundWaterQuality.cy.js, client/cypress/e2e/HomePage.cy.js, client/cypress/e2e/Streamflow.cy.js, client/cypress/e2e/SurfaceWaterQuality.cy.js, client/cypress/e2e/Watershed.cy.js, client/src/components/MapFilters.vue, client/src/components/MapSearch.vue, client/src/components/NavBar.vue, client/src/components/Tour.vue, client/src/components/climate/ClimatePage.vue, client/src/components/groundwater-level/GroundwaterLevel.vue, client/src/components/groundwater/GroundWater.vue, client/src/components/home/HomePage.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/surfacewater/SurfaceWater.vue, client/src/components/watershed/Watershed.vue
- Fixes to E2E tests to ensure they run and pass as expected. This includes temporarily removing checks on yearly data selectors, as the data is currently unavailable. 
- Also included are some fixes to the Tour, which has some of its element fetching broken from an earlier code merge.
E2E test suite passing locally.
=> bcwat-236-e2e-test-updates

backend/queries/watershed/get_watershed_by_lat_lng.py, backend/queries/watershed/get_watershed_stations.py
Include licensee in watershed stations response, fix geojson displayed on watershed click
=> Add Licensee to Watershed Stations

client/src/components/MapFilters.vue
- added licensee name to watershed sidebar
=> bcwat-335-add-licensee

backend/routers/climate.py, backend/utils/climate.py, client/src/components/climate/ClimateReport.vue
Create Alternate way to handle current data within the API
=> Handle Current data prototype

backend/database.py, charts/okd/crunchy/PostgresCluster.yaml, charts/openshift/crunchy/templates/PostgresCluster.yaml, charts/openshift/crunchy/values.dev.yaml, charts/openshift/crunchy/values.prod.yaml, charts/openshift/crunchy/values.test.yaml
Attempting to keep the db connections alive. There is presently no ticket related to this work (sorry!)
=> first attempt at keeping db conns alive

backend/database.py, backend/queries/climate/get_climate_station_csv_by_id.py, backend/queries/shared/get_station_by_type_and_id.py, backend/queries/shared/get_station_csv_metadata_by_type_and_id.py, backend/routers/climate.py, backend/utils/shared.py, client/src/components/climate/ClimatePage.vue, client/src/utils/api.js
Initializing CSV Download Functionality for Climate Module.
This should be trivial to replicate across all other modules (specifically streamflow/groundwater level) and act as a good framework for the surface water/groundwater quality modules.
To validate this, click on a point on the climate module and click download data. You can cross reference by goign to one of the other tools and downloading climate csv, and the data should almost match up.
=> 359 climate csv download

airflow/etl_pipelines/scrapers/StationObservationPipeline/StationObservationPipeline.py
Minor inequality change in the `StationObservationPipeline.download_data` method.
=> Changed the check for minimum files downloaded

database_initialization/queries/post_import_queries.py, database_initialization/util.py
Removing all logging alterations
=> removing logging alteration

charts/okd/crunchy/PostgresCluster.yaml, charts/openshift/crunchy/templates/PostgresCluster.yaml, charts/openshift/crunchy/values.dev.yaml, charts/openshift/crunchy/values.prod.yaml, charts/openshift/crunchy/values.test.yaml
=> Adding some keepalives

backend/database.py, backend/queries/watershed/get_watershed_by_id.py, backend/queries/watershed/get_watershed_by_search_term.py, backend/routers/watershed.py, client/package-lock.json, client/package.json, client/src/components/MapSearch.vue, client/src/components/climate/ClimatePage.vue, client/src/components/groundwater-level/GroundwaterLevel.vue, client/src/components/groundwater/GroundWater.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/surfacewater/SurfaceWater.vue, client/src/components/watershed/Watershed.vue, client/src/utils/api.js
Update search bar to search for allocations and watersheds on Watershed page. 
Selecting an allocation selects is on the map, as do watersheds
=> Search bar

.github/workflows/merge.yml, README.md, charts/openshift/airflow/README.md, charts/openshift/airflow/prerequisites/test/PersistentVolumeClaim.yaml, charts/openshift/airflow/values.test.yaml, charts/openshift/crunchy/README.md, charts/openshift/crunchy/values.test.yaml
This includes the changes necessary to get the crunchydb/airflow pods initialized within the test namespace.
I will add a much more comprehensive guide in the future, however, the current READMEs should indicate all of the manual steps of this process. You can validate the secrets have been created properly within the test namespace, and you can see airflow running by port-forwarding the running pod.
=> Init Test Airflow/DB

.github/workflows/merge.yml, charts/openshift/app/values.test.yaml
=> comment out prod deploy

client/src/components/watershed/Watershed.vue, client/src/components/watershed/report/MonthlyHydrologyChart.vue, client/src/components/watershed/report/MonthlyHydrologyTable.vue
Update the values in the monthly hydrology chart to match existing charts
=> 429 hydrology bar chart   incorrect display

client/src/components/MonthlyMeanFlowTable.vue, client/src/components/streamflow/StreamflowReport.vue
Change shading method for yearly rows
Text changes
=> Change shading method

client/src/components/MapFilters.vue, client/src/components/MonthlyMeanFlowTable.vue, client/src/components/NavBar.vue, client/src/components/ReportChart.vue, client/src/components/climate/ClimateReport.vue, client/src/components/groundwater-level/GroundWaterLevelReport.vue, client/src/components/streamflow/SevenDayFlow.vue, client/src/components/streamflow/Streamflow.vue, client/src/components/streamflow/StreamflowStage.vue, client/src/components/surfacewater/SurfaceWater.vue, client/src/components/waterquality/WaterQualityReport.vue, client/src/components/waterquality/WaterQualityReportChart.vue, client/src/components/watershed/report/MonthlyHydrologyChart.vue
https://github.com/bcgov/nr-bcwat/issues/410
Change colours for current lines and ensure they appear in the chart legend
Fix some issues from [Ben's document](https://docs.google.com/document/d/13rSgTc2B4lP8GRW7P9WA_6qDZSxQQV8OglaMspR8OTc/edit?tab=t.0) there are still a few things left to address
=> 435 ben document changes

charts/openshift/crunchy/values.dev.yaml
Update Dev DB DataVolume/WalStorage to prevent WAL OOM
=> Update Dev DB Storage/Wal

client/src/constants/model-information.js
Updated the methodology statistics for watershed reports from KWT and Cariboo:
KWT:
Cariboo:
=> Update model error with cariboo and kwt values

airflow/etl_pipelines/scrapers/QuarterlyPipeline/quarterly/ems_archive_update.py
Added a little bit more logs to know what's happening and decreased the batch count
=> add row count log, and decreased batch count

.github/workflows/foundry.okd.on-push.application.yaml, .github/workflows/merge.yml
Upping timeout, will merge into main once in!
=> fix flyway timeouts

.github/workflows/foundry.okd.on-push.application.yaml, .github/workflows/merge.yml, client/package-lock.json, client/package.json
Fix Timeout Issue on Test Deployment
=> Fix Timeout Issue for Flyway Migrations on Test Deployment

client/src/components/streamflow/FlowMetrics.vue
Add a descriptive paragraph to the Flow Metrics table
=> Add a description to flow metrics

.github/workflows/foundry.okd.on-push.application.yaml, backend/queries/shared/get_stations_by_type.py
Create Coalesce, up timeout for OKD deploy once more
=> Coalesce, up timeout into OKD

.github/workflows/merge.yml, .github/workflows/pr-close.yml
Remove Triggers - Force Build 
```
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/fc71b797-b6a1-456a-81ef-86a3ea0c68aa' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/nr-bcwat/nr-bcwat
/usr/bin/git config --local --get remote.origin.url
https://github.com/bcgov/nr-bcwat
Removing previously created refs, to avoid conflicts
/usr/bin/git submodule status
Cleaning the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git …
```
=> Remove Triggers - Force Build of all on merge

.github/workflows/.airflow-deployer.yml, airflow/pod_templates/openshift/heavy_task_template.yaml, airflow/pod_templates/openshift/largest_task_template.yaml, airflow/pod_templates/openshift/medium_task_template.yaml, airflow/pod_templates/openshift/small_task_template.yaml, airflow/pod_templates/openshift/tiny_task_template.yaml
Fix Explicit Declaration of the Airflow Connections, Add helm install airflow repository to Github Action
=> Fix airflow helm deploy

client/package-lock.json, client/package.json
One of the negatives of this PR based approach
=> Manually Bump Verison, kick off test deploy

.github/workflows/.airflow-deployer.yml, .github/workflows/pr-open.yml
Tweak Triggers, Airflow Deploy
=> Remove Triggers, Tweak Airflow Deploy

client/src/components/MapFilters.vue, client/src/components/surfacewater/SurfaceWater.vue
We changed the name of the surface water quality module to be "Water Quality Stations" but didn't update the call here, just updated.
=> Update name in check to be Water Quality Stations

client/src/components/watershed/report/Topography.vue
Hide legend for Topography chart when there is no min/max values
=> Hide legend when watershed doesn't have min/max

.github/workflows/merge.yml, README.md
Out of office documentation - I hope this breeds confidence and properly details the instructions to spin up any environment on the chance that something goes haywire.
If something does go majorly wrong, do not hesitate to reach out!!!
=> Liam away documentation updates

backend/database.py, backend/documentation/openapi.json, backend/queries/watershed/get_place_by_name.py, backend/routers/watershed.py, client/package-lock.json, client/package.json, client/src/components/MapFilters.vue, client/src/components/MapSearch.vue, client/src/components/watershed/Watershed.vue, client/src/utils/api.js
Add an API route to search for place names rather than query the API
Add indicator for current licence vs active application on watershed page
Remove network filter from watershed page. We will need to consult with Ben to see about adding the replacement filter values
=> 548 uat   filters for search barsearching in the water module   abby morgan

documentation/knowledge_transfer_documentation.md
Your changes have been applied to this PR
=> changes to the document

client/src/components/MapSearch.vue, client/src/components/watershed/Watershed.vue
Searching lng/lat coordinates on watershed page will attempt to find the watershed at that location
=> Searching by lat/lng on watershed page selects a watershed

.github/workflows/merge.yml, .github/workflows/prod_deploy.yaml
I need to merge this into dev to test its workflow_dispatch capabilities. (cannot run github action from workflow_dispatch unless it exists in repository master branch)
=> Nr bcwat 580 prod manual deploy action

.github/workflows/merge.yml
Fix up tagging so this works on merge of dev into main
=> tagging, do it better with better needs/targets

airflow/etl_pipelines/tests/test_wsc_hydrometric.py
`test_wsc_hydrometric.py` was broken due to changes that were made to the model. But now that the development of the scrapers are finished, the tests have been updated to function
Closes #271
=> Bcwat 271 revamp wsc hydrometric tests

airflow/etl_pipelines/tests/conftest.py, airflow/etl_pipelines/tests/test_functions.py, airflow/etl_pipelines/utils/functions.py
Finished writing Tests for `functions.py`. It uses a `MockDbConn` class that is a `MagicMock` of the connection and cursor. I made this because I didn't want to flood the code with
```Python
fake_conn = MagicMock()
fake_cursor = MagicMock()
fake_conn.cursor.return_value = fake_cursor
```
So it looks a bit cleaner.
I also tried to initialize the `MockDbConn` object in the `conftest.py` file and import that, but then the `reset_mock` method didn't work as expected and it kept on throwing me errors.
Closes #272
=> finished tests for functions.py

backend/main.py, client/nginx.conf, client/nginx.conf.okd.template, client/nginx.conf.openshift.template, client/package-lock.json, client/package.json, client/src/buildEnv.js, client/src/router/index.js, client/src/utils/constants.js, client/vite.config.js
A bunch of changes to deal with issues in the ZAP security scanner:
1. Added root return of healthy to API when hit so no error is passed through
2. Added redirect to root url on not found values in vue router
3. Added sitemap.xml and robots.txt using [Sitemap](https://www.npmjs.com/package/vite-plugin-sitemap). Needed to create a new buildEnv.js to get the root url correctly.
4. Added sri vite package to auto-generate integrity field on npm build
5. Changed nginx.conf to not response to PATCH or TRACE requests, and also add the COOP header to responses.
=> ZAP Security Fixes

client/vite.config.js
Using spec as defined here : https://vite.dev/config/, specify the "development" flag to allow for vite to only install the necessary modules if mode == development to fix dev cypress E2E tests trying to do a more complex build.
=> Change for mode == development

.github/workflows/.unit-tests.yml, .github/workflows/dev-pr-run-unit-tests.yml, .github/workflows/pr-open.yml, client/cypress.config.js, client/vite.config.js
Testing E2E functionality with vitePreprocessor omitted from Cypress Config
=> Rm vitepreprocess cypress config test

.github/workflows/.airflow-deployer.yml, .github/workflows/.deployer.yml, .github/workflows/foundry.okd.on-push.application.yaml, .github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/prod_deploy.yaml, charts/okd/airflow/values.yaml, charts/okd/app/templates/backend/templates/deployment.yaml, charts/okd/app/values.yaml, charts/openshift/airflow/values.dev.yaml, charts/openshift/airflow/values.prod.yaml, charts/openshift/airflow/values.test.yaml, charts/openshift/app/templates/backend/templates/deployment.yaml, charts/openshift/app/values.prod.yaml, charts/openshift/app/values.yaml, client/package-lock.json, client/package.json
The purpose of this PR is to rework when migrations occur within our pipeline. 
Previously, it was identified that applying database migrations to the dev database on PR Open was a major oversight and could cause extensive issues. Since this point, the team has reached an agreement that the best place for database migrations to occur is on merge into main - as this ensures that everyones dev database is in the same state. 
The only issue is that any erroneous migrations that are applied immediately go into the test environment - which could be mitigated against by splitting our pipeline into 2 target branches (dev/main) that will handle the various deployments. 
This was verified to have worked on OKD, if there are any issues with the dev/test/prod pipelines they should be easy to …
=> 607 flyway migrations

client/package-lock.json, client/package.json
Fix Images Built for Airflow Migrations
=> Airflow Migrations needs same image as airflow

documentation/knowledge_transfer_documentation.md
Updates made to the following sections:
- How changes are made to the model
- Implementation process for updates or code fixe
Trying to detail how it works having a single dedicated dev database updated on merge into main. There is potential for issues if care is not taken with the data model updates, however, I am not too stressed about this. I hope this makes sense. The main worry I have is someone making data model changes and being unable to test the API with said changes, as the dedicated dev db is not updated as of yet. 
Let me know if I do not adequately describe mitigation steps.
Lastly, I do not know where to add Disaster recovery docs - should this be within the knowledge transfer document? should I make a new section? Or should I make a new file? 
The focus of that document …
=> Updated Documentation after Migration Pipleine Change

documentation/knowledge_transfer_documentation.md
very minor documentation update for the `Climate` section of the `knowledge_transfer_documentation`
Closes #636
=> documentation update

backend/queries/climate/get_climate_stations.py, backend/queries/shared/get_stations_by_type.py, backend/queries/streamflow/get_streamflow_stations.py, migrations/sql/V1.0.7__update_falsy_not_available_stn.sql
Made sure that the stations that have status' `Not Available` actually doesn't have any data. If they do have data, they have been changed to `Historical` status.
Furthermore, the queries that collect all the stations does not fetch any stations that have `Not Available` as their status.
Closes #536
=> flyway migration and query updates

charts/openshift/backup-db/backup.yaml, charts/openshift/backup-db/knp.yaml, charts/openshift/crunchy/values.prod.yaml, charts/openshift/restore-db/restore.yaml
Upping WAL PVC as it was previously filling up and crashing.
Other edits were latest updates to backup/restore jobs.
=> Up Wal PVC Size

charts/openshift/crunchy/values.prod.yaml
ReInit PgBackrest on Production
=> Enable PGBackRest on Production

client/src/components/MapFilters.vue
- added a small check on whether the text in the search field is null or empty string, and handle filtering accordingly. (this will occur on field clear)
- included a small check to ensure the selected point when point is no longer included in the filtered map points, is removed and does not make a needless failing API call. 
This PR does not address the opened issue surrounding the map listing/filtering.
=> map filtering search fix
