bcgov/nr-bcwat

client/src/components/MapFilters.vue
client/src/components/streamflow/Streamflow.vue
client/src/components/watershed/Watershed.vue

This addition adds a listing of the currently displayed points from the map in the right-hand sidebar. This exists for the Watershed view and improves on the current implementation by adding virtual scroll to reduce the load on rendering a large number of points in a list. Additionally, the sidebar point list was given some user interaction.
- added listing of points to the streamflow view
- modified current MapFilters point list to use virtual scroll
The hover event listener is merely a placeholder. The functionality may not be desired.

Streamflow points sidebar populating with points

---

airflow/pod_templates/simple_task_template.yaml
charts/airflow/README.md
charts/airflow/values.base.yaml
charts/app/Chart.yaml
charts/nfs-server/README.md
charts/nfs-server/okd/persistentvolume.yaml
charts/nfs-server/okd/persistentvolumeclaim.yaml

PVC Created for persistent logging of Airflow Pods.
Configured for Foundry OKD, some changes will need to be initialized to work on BCGov openshift. Namely, location of NFS Server.
This is quite simple. I have updated the READMEs, let me know if not suitable. Basically, prior to this being installed, it requires a DB to be created for Airflow Metadata, as well as a PV/PVC to be created called airflow-logs. Once this is done, everything should be smooth.

Configure PV/PVC, logging, on OKD cluster

---

client/src/components/streamflow/MonthlyMeanFlow.vue
client/src/constants/monthlyMeanFlow.json

Including the Monthly Mean Flow table in the streamflow report popup. This includes a table with gradient shading based on the values for each row for the indicated years, as well as for minimum, maximum, and mean rows. 
- introduced a new table
- added color gradient handling within the table
- added a fixture data file for monthly mean flow data
This table only uses fixture data for now. In the future, changes will be made to use an API call. The `getTableData` function has been set up to serve this purpose in the future, so all that needs to be done is update the function to await the API response.

Bcwat 52 monthly mean flow

---

client/src/components/streamflow/SevenDayFlow.vue
client/src/components/watershed/report/Notes.vue

`npm build` has been failing for our Docker images.
These changes address the error causing the failure, as well as CSS warnings produced.

Fix Npm Run Build

---

.github/workflows/pr-open.yml

Remove Auto Deploy on PR Creation
Will be turned on in the future, however we must initialized a dedicated dev database initialized, rather than the DB per PR Open

RM deploy on PR Open

---

.github/workflows/foundry.okd.on-push.application.yaml
airflow/Dockerfile
charts/okd/airflow/README.md

Working on locking airflow version, mitigating against future updates.
New feature (non-breaking change which adds functionality) 
Documentation (non-breaking change with enhancements to documentation) 
Set Docker Image to use python3.12, lock chart to 1.16.0 for now.
https://helm.sh/docs/helm/helm_install/
Check out the version flag that we are using.
Also, you can validate the latest chart version is 1.16.0: https://artifacthub.io/packages/helm/apache-airflow/airflow

Lock Chart Verison, Update to python3.12

---

airflow/pod_templates/heavy_task_template.yaml
airflow/pod_templates/medium_task_template.yaml
airflow/pod_templates/simple_task_template.yaml
charts/okd/app/templates/backend/templates/deployment.yaml

Mitigate against API OOMing (think its OOMing on load of that massive JSON fixture)
Prevent Pods from getting scheduled on worker0 (not polars compatible)
To test this out, we gotta merge in the quarterly hydat branch, and trigger DAG and see what happens!

Up API Resources, initialize Node Affinity for Worker Pod Templates

---

charts/okd/airflow/values.yaml

Started Encountering an issue within our Airflow Worker Pods, where they were trying to pull our private image, and rightfully failing.
Worker Pods were failing immediately for the following reason:
```
status:
containerStatuses:
- name: base
state:
waiting:
reason: ImagePullBackOff
message: 'Back-off pulling image "foundrymainregistry.azurecr.io/bcwat/airflow:3.2.1"'
lastState: {}
ready: false
restartCount: 0
image: 'foundrymainregistry.azurecr.io/bcwat/airflow:3.2.1'
imageID: ''
started: false
```
This is odd to me because we explicitly tell the worker pods to just use the base Airflow Image:
```
containers:
- name: base
image: apache/airflow:2.10.5
imagePullPolicy: IfNotPresent
```
However, my assumption is the interaction between the …

Debugging Airflow Image Issue

---

airflow/pod_templates/heavy_task_template.yaml
airflow/pod_templates/medium_task_template.yaml
airflow/pod_templates/simple_task_template.yaml
charts/okd/airflow/values.yaml

I guess we do need to pass the acr-pull-secret in - as the image is being overridden, and now the dagbag is no longer populated by the scheduler?
I do not know what changed, but since the last major update, the worker templates were updated use the base image from the images.airflow block. Previously, I used the base airflow image block. Furthermore, the dagbag needs to be included within the image the worker pods use - before hand, it could be separate (I believe it got populated via triggerer/scheduler/webserver)?
I hope this works!
Furthermore, this will need to be revisited once we have it on BCGov Openshift. Because they will not have a pull secret. We will cross the bridge when we come to it.

Hard Set imagePullSecret

---

client/src/utils/api.js

API Environment variables not loading on deployment.
This is based upon how we reference environment variables on the FE differently on this project.
https://bcwatertool.fspatial
You should be able to validate that the Map appears as expected, but the API routes fail (because they are making requests to the incorrect URL)
Furthermore, you can verify that this provides the API_URL as we expect.

Update the reference to the FrontEnd Env Vars in Api.js

---

airflow/etl_pipelines/scrapers/QuarterlyPipeline/quarterly/ems_archive_update.py
airflow/etl_pipelines/scrapers/QuarterlyPipeline/quarterly/water_quality_eccc.py
airflow/etl_pipelines/scrapers/StationObservationPipeline/StationObservationPipeline.py
airflow/etl_pipelines/utils/constants.py
airflow/etl_pipelines/utils/functions.py

Minor changes to fix errors occuring in the scraper DAGs:
- Change min ratio to be a float value instead of dict.
- Asked Ben what these values should be, and he said that 0 is fine, since if the BC Gov want something more specific, they can change it themselves.
- Column that was being referenced was wrong, so fixed.

Minor scraper fixes

---

backend/utils/climate.py
backend/utils/groundwater.py
backend/utils/shared.py
backend/utils/streamflow.py
client/src/components/streamflow/SevenDayFlow.vue

Every Historical Entry for climate, streamflow, and groundwater now creates a series from 1 - 366, containing null data for all columns where data not found.
To Validate, navigate to climate/streamflow/groundwater, and check the historical records. You wll notice the time series now does not skip days.
```
{
"d": 7,
"p10": 573.0,
"p25": 573.0,
"p50": 573.0,
"p75": 573.0,
"p90": 573.0
},
{
"d": 26,
"p10": 535.0,
"p25": 535.0,
"p50": 603.0,
"p75": 634.0,
"p90": 872.0
},
```
Previous ^
```
{
"d": 7,
"p10": 573.0,
"p25": 573.0,
"p50": 573.0,
"p75": 573.0,
"p90": 573.0
},
{
"d": 8,
"p10": null,
"p25": null,
"p50": null,
"p75": null,
"p90": null
},
{
"d": 9,
"p10": null,
"p25": null,
"p50": null,
"p75": null,
"p90": null
},
{
"d": 10,
"p10": null,
"p25": null,
"p50": null,
"p75": null,
"p90": …
```

Ensure Every Historical Record has entry for each day. Null Fill

---

client/src/components/climate/ClimateReport.vue
client/src/components/streamflow/StreamflowReport.vue

Added watchers to StreamflowReport.vue and ClimateReport.vue that will update the viewPage to only show a page with data available. Some other small fixes, fixed a console.error for climate reports without snow depth but with temperature.
To test, please check out different streamflow and climate reports with different data availability and see that a chart with data available is opened when the page is.

Nr bcwat 438 data tab only

---

airflow/etl_pipelines/utils/database.py
charts/okd/app/templates/backend/templates/deployment.yaml
charts/okd/app/values.yaml
charts/okd/crunchy/PostgresCluster.yaml
charts/openshift/crunchy/values.dev.yaml
migrations/sql/V1.0.4_db_user_permissions.sql

Initialize PgBouncer for handling our Connection Pool on OKD.
The goal of this is to provide the framework for handling connections to our crunchy databased on Openshift.
Enable PgBouncer, create new users, include permissions that were manually applied within the migrations table. Will discuss with Kash what to do about db migrations on flyway once he has returned.

Pgbouncer test on okd

---

migrations/sql/V1.0.3__fix_in_study_area_falgs.sql

Noticed that some areas in Omineca didn't generate a watershed report on click. This was because the `in_study_area` flag wasn't properly set for some of the watersheds in the `fwa_funds` table.
This migration will fix those values.

adding flyway migration that updates `in_study_area` flag

---

charts/openshift/airflow/prerequisites/prod/PersistentVolumeClaim.yaml
charts/openshift/airflow/values.prod.yaml
charts/openshift/crunchy/values.prod.yaml
charts/openshift/restore-db/knp.yaml
charts/openshift/restore-db/restore.yaml

Simple Init of Prod Database, created via command within README. 
I will be automating this process in the future.
Furthermore, I will turn pgbackrest on in the future - I would like to experiment with it OnPrem before backing up to s3 from openshift

Initializing Prod DB with replicas, defaulting pgbackrest off (for now)

---

client/src/components/watershed/Watershed.vue
client/src/components/watershed/report/MonthlyHydrologyChart.vue
client/src/components/watershed/report/MonthlyHydrologyLegend.vue

Add loader to watershed page when loading a watershed polygon
Change how existing allocations are displayed. They now extent down the chart as a means of identifying how much of the available water has been allocated

Change allocations display. Add watershed loader

---

backend/database.py

Very simple change to raise the max number of connections our connection pool in pythin can have now that we have initialized pgbouncer to do the real pooling behind the scenes (maxconn in python now represents max length of the 'queue' per worker)
Closes: [#514](https://github.com/bcgov/nr-bcwat/issues/514)

raising max connections

---

charts/openshift/crunchy/templates/PostgresCluster.yaml
charts/openshift/crunchy/values.prod.yaml

Added some limits to the pgbackrest job so we wouldn't have a huge spike in memory as we saw before. We were able to manually run a incremental and full backup and both worked in reasonable amounts of time.

added some limits to pgbackrest job

---

.github/workflows/scheduled.yml

Removing schemaSpy from the github action that is scheduled to run once a week. It has been consistently failing as its local DB it spins up does not have the context of our restored db and therefore it fails to run the flyway migrations on it. I don't think it's worth the effort to try and make work as we already have detailed db documentation. Please let me know if we need to keep it Liam!

removing schema spy as it auto-fails
